### ISSUE TITLE
Question: what purpose does the Dev wallet and Emulator toggles serve?

### ISSUE THREAD

**Issue by bymi15** [onflowser/flowser#136]
**Is your feature request related to a problem? Please describe.**
Do these toggles serve any purpose?
Is there a usecase for disabling these toggles or can they just be enabled by default?
![image](https://user-images.githubusercontent.com/14804687/198694603-503c6e8a-c29e-40b1-9c8f-652f5f7fe2f4.png)

**Comment by bartolomej** [comment]
Hey @bymi15, thanks for trying out Flowser and giving us some early feedback!

Hmm, yeah that's definitely something we need to better explain!

Basically, those toggles control whether the Flowser app starts (manages) the Flow emulator / fcl-dev-wallet tools automatically or not.

So if those toggles are on, Flowser will start those tools with the provided settings (visible if you toggle "advanced settings") and also make sure they are stopped after you close the project, restarted when project settings are changed, etc...

If you keep those toggles off, you will need to start/manage those tools yourself by running `flow emulator <settings-flags>` or `flow dev-wallet <settings flags>`.

Does that make more sense?

Do you think that it would be clear enough if we just added some labels next to the toggles (e.g. "Run dev wallet")? Or maybe we should even add a clearer & longer explanation somewhere in the settings page.

**Comment by bymi15** [comment]
Oh I see that makes a lot more sense.
Thanks for the response.

In that case, I definitely think a label or description would be helpful.

**Comment by bartolomej** [comment]
Closed by #144

**Comment by bartolomej** [comment]
@bymi15 This should be as of [v2.0.6-beta release](https://github.com/onflowser/flowser/releases/tag/v2.0.6-beta).

FYI you can now also run flower with Flow CLI command:

```bash
flow flowser
```

See https://github.com/onflowser/flowser#get-started
