### ISSUE TITLE
Service account distinction

### ISSUE THREAD

**Issue by sideninja** [onflowser/flowser#155]
It would be useful to visually distinguish the service account in the accounts table, something like a tag would work. Now all accounts are presented the same way so it takes a bit of understanding to know the service account. The service account is defined in flow.json.

![Screenshot 2022-12-22 at 14 08 09](https://user-images.githubusercontent.com/75445744/209141318-bc5c184b-3631-4fde-baf3-f7fee53cc4ca.png)

**Comment by bartolomej** [comment]
Resolved in https://github.com/onflowser/flowser/pull/187
