### ISSUE TITLE
Account balance doesn't get updated in UI

### ISSUE THREAD

**Issue by bartolomej** [onflowser/flowser#161]
**Describe the bug**

After executing the [transfer FLOW transaction](https://github.com/onflow/flow-core-contracts/blob/master/transactions/flowToken/transfer_tokens.cdc), balances don't get properly updated in Flowser UI.

**Comment by cybercent** [comment]
Is this project dead?

**Comment by bartolomej** [comment]
@cybercent No. We've been quiet for the last couple of months, but we have big plans moving forward! 🚀 

We just started the work for our latest grant here: https://github.com/onflow/developer-grants/issues/150

So I think you can expect these issues to get resolved soon.
