### ISSUE TITLE
Use array args in transactions that are sent via the UI

### ISSUE THREAD

**Issue by cybercent** [onflowser/flowser#162]
**Is your feature request related to a problem? Please describe.**
Send a TX via Flowser UI that accepts array arguments

**Describe the solution you'd like**
The list of possible types does not contain an Array.
Add an `Array<Type>` field.

**Comment by bartolomej** [comment]
Hey @cybercent, thanks for the report!

FYI we are planning to implement this (along with revamping the transaction UI completely) in the scope of our upcomming grant: https://github.com/onflow/developer-grants/issues/150.

**Comment by bartolomej** [comment]
As an update, the solution for this is already in the works for some time in the scope of this PR: https://github.com/onflowser/flowser/pull/170
