### ISSUE TITLE
typo on flowser.dev website

### ISSUE THREAD

**Issue by bthaile** [onflowser/flowser#198]
**Describe the bug**
typo "Flowser guides you thought your dev journey with an easy to use GUI."

"thought" should be "through"

**To Reproduce**
goto: https://flowser.dev/

notice the typo on the page. 

**Screenshots**

![image](https://github.com/onflowser/flowser/assets/3970376/2c8a2dc4-42c4-4193-b467-317c4d8f1cad)

**Comment by bartolomej** [comment]
@bthaile Good eye! Thanks for reporting this. 

Fixed in https://github.com/onflowser/website/commit/6d2783a975568a8752ba34cbec168c271ae379ff.
