### ISSUE TITLE
isNew & isUpdated classes on frontend are fishy

### ISSUE THREAD

**Issue by jgololicic** [onflowser/flowser#43]
Looks like isNew animation when adding new data is not working as expected. Investigate and fix

**Comment by bartolomej** [comment]
Also `useTimeoutPolling` hook has a bug in result mapping logic. Those those empty rows appear very often.

**Comment by bartolomej** [comment]
In some cases it also shows invalid number of accounts (some items are duplicated), there is a total of 3 accounts in the db, but UI shows this:

<img width="1427" alt="Screenshot 2021-11-06 at 19 10 35" src="https://user-images.githubusercontent.com/36109955/140619614-d67ffb84-8629-403e-b808-38b33bbd0b5c.png">

**Comment by jgololicic** [comment]
1. Solved polling problem
2. Fixed messed up layout
