### ISSUE TITLE
Invalid data for account storage

### ISSUE THREAD

**Issue by bartolomej** [onflowser/flowser#52]
Storage account data doesn't get formatted.

This is the exact data returned for account in demo: https://pastebin.com/raw/DH5DRqXH

![Screenshot 2021-11-03 at 17 16 36](https://user-images.githubusercontent.com/36109955/140099834-efa9f29a-d816-466c-8f1c-5486f98d8557.png)

**Comment by jgololicic** [comment]
We encounter this error when data is partially missing. That issue had been partially fixed, but better solution could be found. I will leave it open for a while and revise it later

**Comment by bartolomej** [comment]
Closing this since we rewrote the storage functionality from scratch.
