### ISSUE TITLE
Improve logging view UX

### ISSUE THREAD

**Issue by bartolomej** [onflowser/flowser#58]
> all the requests going to the emulator make the emulator logs very chatty and relevant information can quickly get buried. I wonder if the logs could be presented better or the chattiness somehow reduced. - https://github.com/onflow/flip-fest/pull/89#issuecomment-958118594

We should think about the best way to improve this. Maybe wait for more feedback in mentioned PR.

- [ ] better use horizontal space for logs - I'm viewing this on 13inch macbook and each log line spans only half of my screen width, because of the text break. This should be improved in some way. Maybe we could display logs in oneline (without text break) and add horizontal scroll.
<img width="1439" alt="Screenshot 2021-11-04 at 14 31 17" src="https://user-images.githubusercontent.com/36109955/140322090-65cf5b74-575c-411f-90ef-144e25204e87.png">

**Comment by jgololicic** [comment]
word-break changed to break-all
