### ISSUE TITLE
UI/UX polishes

### ISSUE THREAD

**Issue by bartolomej** [onflowser/flowser#59]
> Do make an extra effort for the final milestone to make sure the UI is polished, and visually consistent. If we're going to feature your project in the community, you want to make sure to put your best foot forward. - https://github.com/onflow/flip-fest/pull/119#issuecomment-961464243

- [x] make sure table columns have consistent width and alignment
- [x] reduce SubNavigation height

**Comment by jgololicic** [comment]
Here we need to rethink design for smaller screens. We would need at least three additional versions of the UI design:
- 769px — 1024px: Small screens, laptops
- 1025px — 1200px: Desktops, large screens
- 1201px and more —  Extra large screens, TV

**Comment by bartolomej** [comment]
Agreed, I created a seperate issue, as this is not a minor change.
