### ISSUE TITLE
Logged in message appears when canceling FCL Dev wallet popup

### ISSUE THREAD

**Issue by jgololicic** [onflowser/flowser#66]
How to reproduce:
1. Open FCL Dev Wallet login popup dialog by clicking "LOG IN" button
2. Click "X" close button on top right corner of the dialog

Unexpected result:
- "Logged in!" snack bar info message appears 

Expected result:
- No info snack bar message should appear

**Comment by bartolomej** [comment]
Fixed in bead71dc7ef41142403b192c2e693e0171e68b08.
