### ISSUE TITLE
fcl-dev-wallet integration with user managed emulator not working

### ISSUE THREAD

**Issue by bartolomej** [onflowser/flowser#72]
**Describe the bug**
Feedback from Flow team:
> The default emulator doesn’t show any data, and the wallet doesn’t work. I had to add a custom emulator from the home page. It may be related to this issue: https://github.com/onflowser/flowser/issues/23

**Comment by bartolomej** [comment]
Currently there is no way to make dev-wallet work with flowser and user managed emulators, because the former run on port `A` and latter run on some other port `B`. 

dev-wallet requires us to define `FLOW_ACCESS_NODE` at build time, (see https://github.com/onflowser/flowser/blob/master/docker-compose.yml#L87), tso here is no way to dynamically change access node url (e,g, from http://localhost:8080 - flowser managed emulator to http://localhost:8081 - user managed emulator).

One possible solution would be to add this functionality to dev-wallet, what are your thoughts @jgololicic ?

**Comment by bartolomej** [comment]
I added a info prompt with simple instructions for how to connect flowser to default emulator:
![Screenshot 2021-12-31 at 20 23 04](https://user-images.githubusercontent.com/36109955/147836883-db54ffc3-dc8b-481a-92ef-42fc001aad00.png)

**Comment by psiemens** [comment]
> dev-wallet requires us to define FLOW_ACCESS_NODE at build time, (see https://github.com/onflowser/flowser/blob/master/docker-compose.yml#L87), tso here is no way to dynamically change access node url (e,g, from http://localhost:8080 - flowser managed emulator to http://localhost:8081 - user managed emulator).

I just want to make sure I'm understanding the problem correctly. Is this right?

- Flowser always launches an emulator instance alongside the main app. This emulator runs at the default port 8080
- If a user runs an emulator instance outside of Flowser without changing the config (e.g. `flow emulator start`), the default port will clash with the instance that Flowser is running
- However, Flowser will connect to an external (user managed) emulator on port 8081, but _only if it is running_
- The dev wallet is configured in `docker-compose.yml` when Flowser launches, so there's no way to redirect the dev wallet at port 8081 once Flowser detects an emulator running there

**Comment by bartolomej** [comment]
@psiemens 

> Flowser always launches an emulator instance alongside the main app. This emulator runs at the default port 8080
  
Yes, Flowser exposes (allocates) the default emulator ports (http=8080, rpc=3569), defined [here](https://github.com/onflowser/flowser/blob/master/docker-compose.yml#L21-L22).


> If a user runs an emulator instance outside of Flowser without changing the config (e.g. flow emulator start), the default port will clash with the instance that Flowser is running

That's true. This will happen even if the emulator that is managed by Flowser is not running, because docker allocates port resources when containers are started.


> However, Flowser will connect to an external (user managed) emulator on port 8081, but only if it is running

Also true, Flowser will connect to a predefined "user emulator" port, that is set with env variable `USER_MANAGED_EMULATOR_PORT`, but could also be defined at run-time by the user himself (e.g. through some in app setting). [Here](https://github.com/onflowser/flowser/blob/master/backend/src/projects/projects.service.ts#L84) is the code block that handles user managed emulator port setting.


> The dev wallet is configured in docker-compose.yml when Flowser launches, so there's no way to redirect the dev wallet at port 8081 once Flowser detects an emulator running there

Yep, thats exactly right. Thats the core of this issue.

**Comment by bartolomej** [comment]
Closing this since we completely rewrote that logic in https://github.com/onflowser/flowser/releases/tag/v2.0.0-beta
